# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  push:
    tags:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Create Release
        uses: TheDoctor0/zip-release@0.6.0
        with:
          type: 'zip'
          filename: 'swim-wp-cli.zip'
          exclusions: '*.git* composer.lock README.md'

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'swim-wp-cli.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
